### PR TITLE
Arrow c20

### PR DESCRIPTION
**Pull request by arrowarchive**
@ebeshero This branch is ready for review after everything "on heart of Felix" and the alignment caused. Hopefully it's good to go

### CODE REVIEW

**Comment by ebeshero** [comment]
I'm leaving this one open to try and work on the remaining issues!

**Comment by ebeshero** [comment]
@Yuying-Jin @nhammer514 I think I've finally repaired Rachel's C20 branch with a lot of longToken puzzling. There's a long stretch in the middle of this unit where the MS doesn't have anything, and I think I've managed to correctly line up about where it stops and where it starts. There is one phrase in the MS that I think arguably should be at the other side of the gap, but I don't think it matters very much, and we could always edit it by hand later. The phrase is wrapped in a longToken: The normalized token comes at the end of the tag: 

```xml
['...other tokens...',  'the merchant   commander   &lt;del&gt;her&lt;/del&gt; his daughter']">
```
Here's the passage in fMS:

```xml
&lt;longToken&gt;&lt;sga-add place="superlinear" sID="c57-0033__main__d4e5468"/&gt;the merchant &lt;sga-add eID="c57-0033__main__d4e5468"/&gt; &lt;mod eID="c57-0033__main__d4e5463"/&gt; commander &lt;lb n="c57-0033__main__13"/&gt;&lt;mod sID="c57-0033__main__d4e5475"/&gt; &lt;del rend="strikethrough" xml:id="c57-0033__main__d4e5477"&gt;her&lt;/del&gt; &lt;sga-add place="superlinear" sID="c57-0033__main__d4e5480"/&gt;his daughter&lt;sga-add eID="c57-0033__main__d4e5480"/&gt;&lt;mod eID="c57-0033__main__d4e5475"/&gt;&lt;/longToken&gt
```

I don't think I can persuade the collation to move this--I've tried several combinations of longTokens and I think this is about the best we can do here. But I think it should stack in this app, MUCH further along, just as the MS rejoins the other witnesses:

```xml
['...other tokens...', 'the merchant commanded his daughter']">
```

(That's also wrapped in a longToken in all the other witnesses.) I don't think it matters to keep trying to correct it because at least this collation properly separates the MS from the other witnesses at the long stretch where it really is completely missing. 

 So I think we should go ahead and merge this PR.

**Comment by ebeshero** [comment]
After we merge this to `main`, please delete the branch!

**Comment by Yuying-Jin** [comment]
@ebeshero `lux urious` in MS has an extra space in the middle. We add the space with this regex `RE_SPACE_LB = re.compile(r'([\w\s])<lb.*?/>')` in collate.py. 
```xml
<app>
        <rdgGrp n="['and', 'luxurious', 'city,']">
	        <rdg wit="f1818">and luxurious city,</rdg>
	        <rdg wit="f1823">and luxurious city,</rdg>
	        <rdg wit="fThomas">and luxurious city,</rdg>
	        <rdg wit="f1831">and luxurious city,</rdg>
        </rdgGrp>
        <rdgGrp n="['and&lt;w ana=&#34;start&#34;/&gt;', 'lux urious', 'city']">
	        <rdg wit="fMS">&amp;&lt;w ana="start"/&gt; lux&lt;lb
		        n="c57-0031__main__18"/&gt;urious&lt;w ana="end"/&gt; city</rdg>
        </rdgGrp>
</app>
```
According to the comment, the space should not be added inside the `<w>` element tags. 
```python
    normalized = RE_WORD_START.sub(' \\1', normalized)
    # 2023-05-22 ebb and yxj: We must replace WORD_START before the SPACE_LB.
    # WORD_START replacement ensures that the normalized token for <w ana='start'/>...<lb/>...<w ana="end"/>
    # does not get an added space. We need to ensure that these are treated as single word tokens
    # with no space added internally.
    normalized = RE_WORD_END.sub(' ', normalized)
    normalized = RE_SPACE_LB.sub('\\1 ', normalized)
    normalized = RE_LB.sub('', normalized)
```

**Pull request merged**
